# Generated by Django 6.0.4 on 2026-04-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.CharField(max_length=200, verbose_name='用户输入')),
                ('predicted_intent', models.CharField(blank=True, max_length=50, null=True, verbose_name='预测意图')),
                ('confidence', models.FloatField(default=0.0, verbose_name='置信度')),
                ('is_corrected', models.BooleanField(default=False, verbose_name='是否已人工纠正')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '意图识别失败日志',
                'verbose_name_plural': '意图识别失败日志',
                'ordering': ['-created_time'],
            },
        ),
    ]
